---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .  # "." is workaround for ansible-lint >=5.0.0
platforms:
  - name: instance
    image: ${DISTRIBUTION_TO_TEST:-ubuntu:latest}
provisioner:
  name: ansible
verifier:
  name: ansible
