---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint  # No params require version >=4.2.0 of ansible-lint
platforms:
  - name: instance
    image: ${DISTRIBUTION_TO_TEST:-ubuntu:latest}
provisioner:
  name: ansible
verifier:
  name: ansible
